name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up ROS2 environment
        uses: ros/tooling@main
        with:
          ros_distro: humble

      - name: Build ROS2 package
        run: |
          pwd
          ls -A
          cd myname_pubsub
          colcon build

      - name: Check build result
        run: |
          colcon test --return-code-on-test-failure