name: build_test
on: push

jobs:
  colcon-build:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop
    strategy:
      matrix:
        rosdistro:
          - humble
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Apt update
        run: |
          sudo apt update -y

      - name: Build Test
        run: |
          mkdir ../ros2_ws/src -p
          cp -r ./* ../ros2_ws/src
          cd ../ros2_ws
          rosdep update
          rosdep install -r -y --from-paths --ignore-src ./
          source /opt/ros/humble/setup.bash
          colcon  build --symlink-install
        shell: bash