name: colcon build
on: push

jobs:
  colcon-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Set up ROS environment
        uses: ros-tooling/setup-ros@v1.2.0
        with:
          ros_distro: humble
      
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          python3-vcstool \
          wget
      
      - name: Install dependencies for myname_pubsub packages
        run: |
          cd humble_ws && \
          rosdep update && \
          rosdep install --from-paths src --ignore-src -r -y
      
      - name: Build packages
        run: |
          cd humble_ws && \
          colcon build --packages-select myname_pubsub